package ca.usask.gmcte.currimap.model;
// Generated Jan 30, 2012 12:54:19 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OrderBy;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * AnswerSet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "answer_set")
public class AnswerSet implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<AnswerOption> answerOptions = new HashSet<AnswerOption>(0);

	public AnswerSet() {
	}

	public AnswerSet(String name,
			Set<AnswerOption> answerOptions) {
		this.name = name;
		this.answerOptions = answerOptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	@Length(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "answerSet")
	@OrderBy("displayIndex asc")
	public Set<AnswerOption> getAnswerOptions() {
		return this.answerOptions;
	}

	public void setAnswerOptions(Set<AnswerOption> answerOptions) {
		this.answerOptions = answerOptions;
	}

}
