package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;



/**
 * Characteristic generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "assessment_feedback_option")
public class AssessmentFeedbackOption implements java.io.Serializable
{

	private int id;
	private String name;
	private int displayIndex;
	private AssessmentFeedbackOptionType type; //assessment_feedback_option_type_id

	public AssessmentFeedbackOption()
	{
	}


	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	
	@Column(name = "display_index", nullable = false)
	public int getDisplayIndex()
	{
		return this.displayIndex;
	}

	public void setDisplayIndex(int displayIndex)
	{
		this.displayIndex = displayIndex;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assessment_feedback_option_type_id")
	public AssessmentFeedbackOptionType getType()
	{
		return type;
	}


	public void setType(AssessmentFeedbackOptionType type)
	{
		this.type = type;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName()
	{
		return name;
	}


	public void setName(String name)
	{
		this.name = name;
	}

}
