package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;



/**
 * Characteristic generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "assessment_feedback_option_type")
public class AssessmentFeedbackOptionType implements java.io.Serializable
{

	private int id;
	private String question;
	private int displayIndex;
	private String questionType;

	public AssessmentFeedbackOptionType()
	{
	}


	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	
	@Column(name = "display_index", nullable = false)
	public int getDisplayIndex()
	{
		return this.displayIndex;
	}

	public void setDisplayIndex(int displayIndex)
	{
		this.displayIndex = displayIndex;
	}



	@Column(name = "question", nullable = false, length = 300)
	@NotNull
	@Length(max = 300)
	public String getQuestion()
	{
		return question;
	}


	public void setQuestion(String question)
	{
		this.question = question;
	}

	@Column(name = "question_type", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getQuestionType()
	{
		return questionType;
	}


	public void setQuestionType(String questionType)
	{
		this.questionType = questionType;
	}

}
