/*****************************************************************************
 * Copyright 2012, 2013 University of Saskatchewan
 *
 * This file is part of the Curriculum Alignment Tool (CAT).
 *
 * CAT is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 *(at your option) any later version.
 *
 * CAT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with CAT.  If not, see <http://www.gnu.org/licenses/>.
 *
 ****************************************************************************/


package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;



/**
 * Course generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "course")
public class Course implements java.io.Serializable
{

	private int id;
	private String subject;
	private int courseNumber;
	private String title;
	private String description;
	private Set<LinkCourseProgram> linkCoursePrograms = new HashSet<LinkCourseProgram>(0);

	public Course()
	{
	}

	public Course(int id, String subject, int courseNumber, String title)
	{
		this.id = id;
		this.subject = subject;
		this.courseNumber = courseNumber;
		this.title = title;
	}

	public Course(int id, String subject, int courseNumber, String title,
			String description,
			Set<LinkCourseProgram> linkCoursePrograms)
	{
		this.id = id;
		this.subject = subject;
		this.courseNumber = courseNumber;
		this.title = title;
		this.description = description;
		this.linkCoursePrograms = linkCoursePrograms;
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "subject", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getSubject()
	{
		return this.subject;
	}

	public void setSubject(String subject)
	{
		this.subject = subject;
	}

	@Column(name = "course_number", nullable = false)
	public int getCourseNumber()
	{
		return this.courseNumber;
	}

	public void setCourseNumber(int courseNumber)
	{
		this.courseNumber = courseNumber;
	}

	@Column(name = "title", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getTitle()
	{
		return this.title;
	}

	public void setTitle(String title)
	{
		this.title = title;
	}

	@Column(name = "description", length = 1024)
	@Length(max = 1024)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}


//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	@Transient
	public Set<LinkCourseProgram> getLinkCoursePrograms()
	{
		return this.linkCoursePrograms;
	}

	public void setLinkCoursePrograms(Set<LinkCourseProgram> linkCoursePrograms)
	{
		this.linkCoursePrograms = linkCoursePrograms;
	}

}
