package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Outcome generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "course_outcome_group")
public class CourseOutcomeGroup implements java.io.Serializable, Comparable<CourseOutcomeGroup>
{

	private int id;
	private String name;
	private String departmentSpecific;
	private int departmentId;

	public CourseOutcomeGroup()
	{
	}

	public int compareTo(CourseOutcomeGroup other)
	{
		return other.getId() - id;
	}
	
	public CourseOutcomeGroup(int id, String name)
	{
		this.id = id;
		this.name = name;
	}


	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}
	
	@Column(name = "department_specific", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getDepartmentSpecific()
	{
		return this.departmentSpecific;
	}

	public void setDepartmentSpecific(String p)
	{
		this.departmentSpecific = p;
	}
	
	
	@Column(name = "department_id", nullable = false)
	public int getDepartmentId()
	{
		return departmentId;
	}

	public void setDepartmentId(int departmentId)
	{
		this.departmentId = departmentId;
	}

}
