package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Program generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "course_attribute_value")
public class CourseAttributeValue implements java.io.Serializable
{

	private int id;
	private String value;
	private Course course;
	private CourseAttribute attribute;

	public CourseAttributeValue()
	{
	}


	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}


	@Column(name = "value", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getValue()
	{
		return value;
	}


	public void setValue(String value)
	{
		this.value = value;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "course_attribute_id")
	public CourseAttribute getAttribute()
	{
		return attribute;
	}


	public void setAttribute(CourseAttribute attribute)
	{
		this.attribute = attribute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id")
	public Course getCourse()
	{
		return course;
	}


	public void setCourse(Course course)
	{
		this.course = course;
	}
}
