package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import ca.usask.gmcte.currimap.action.ProgramManager;


/**
 * Assessment generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "department")
public class Department implements java.io.Serializable, Comparable<Department>
{

	private int id;
	private String name;
	private String ldapName;
	private List<CharacteristicType> characteristicTypes;
	private List<LinkDepartmentCharacteristicType> linkDepartmentCharacteristicTypes = new ArrayList<LinkDepartmentCharacteristicType>(0);

	public Department()
	{
	}
	public int compareTo(Department other)
	{
		return other.getName().compareTo(this.name);
	}
	public Department(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public List<LinkDepartmentCharacteristicType> getLinkDepartmentCharacteristicTypes()
	{
		return this.linkDepartmentCharacteristicTypes;
	}

	public void setLinkDepartmentCharacteristicTypes(
			List<LinkDepartmentCharacteristicType> linkDepartmentCharacteristicTypes)
	{
		this.linkDepartmentCharacteristicTypes = linkDepartmentCharacteristicTypes;
	}

	@Transient
	public List<CharacteristicType> getCharacteristicTypes()
	{
		if(characteristicTypes == null)
		{
			ProgramManager.instance().setDepartmentCharacteristicTypes(this);
		}
		return characteristicTypes;
	}

	public void setCharacteristicTypes(List<CharacteristicType> characteristicTypes)
	{
		this.characteristicTypes = characteristicTypes;
	}
	@Column(name = "ldap_name", nullable = true, length = 100)
	@Length(max = 100)
	public String getLdapName()
	{
		return ldapName;
	}
	public void setLdapName(String ldapName)
	{
		this.ldapName = ldapName;
	}
}
