package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;


/**
 * Assessment generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "feature")
public class Feature implements java.io.Serializable
{

	private int id;
	private String name;
	private String fileName;
	private int displayIndex;

	public Feature()
	{
	}

	public Feature(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	
	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "file_name", length = 100)
	@Length(max = 1024)
	public String getFileName()
	{
		return this.fileName;
	}

	public void setFileName(String f)
	{
		this.fileName = f;
	}

	

	@Column(name = "display_index", nullable = false)
	public int getDisplayIndex()
	{
		return this.displayIndex;
	}

	public void setDisplayIndex(int displayIndex)
	{
		this.displayIndex = displayIndex;
	}
}
