package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import java.util.TreeMap;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import ca.usask.ocd.ldap.LdapConnection;

/**
 * Program generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "instructor")
public class Instructor implements java.io.Serializable
{

	private int id;
	private String userid;

	public Instructor()
	{
	}


	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "userid", nullable = false, length = 12)
	@NotNull
	@Length(max = 12)
	public String getUserid()
	{
		return this.userid;
	}

	public void setUserid(String userid)
	{
		this.userid = userid;
	}
	@Transient
	public String getInstructorDisplay()
	{
		StringBuilder output = new StringBuilder();
		
		try
		{
			LdapConnection ldapConnection = LdapConnection.instance();
			TreeMap<String,String> data = ldapConnection.getUserData(userid);
			output.append(data.get("givenName"));
			output.append(" ");
			output.append(data.get("sn"));
			
		}
		catch(Exception e)
		{
			output.append("Unable to retrieve instructor name");
		}
		output.append("( ");
		output.append(userid);
		output.append(" )");
		return output.toString();
	}
}
