package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



/**
 * Characteristic generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "link_course_assessment_feedback_option_value")
public class LinkCourseAssessmentFeedbackOption implements java.io.Serializable
{
	private int id;
	
	private LinkCourseOfferingAssessment linkCourseOfferingAssessment;
	private AssessmentFeedbackOption option; //assessment_feedback_option_type_id

	public LinkCourseAssessmentFeedbackOption()
	{
	}


	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "link_course_offering_assessment_id")
	public LinkCourseOfferingAssessment getLinkCourseOfferingAssessment()
	{
		return linkCourseOfferingAssessment;
	}


	public void setLinkCourseOfferingAssessment(
			LinkCourseOfferingAssessment linkCourseOfferingAssessment)
	{
		this.linkCourseOfferingAssessment = linkCourseOfferingAssessment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assessment_feedback_option_id")
	public AssessmentFeedbackOption getOption()
	{
		return option;
	}


	public void setOption(AssessmentFeedbackOption option)
	{
		this.option = option;
	}

}
