package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * LinkProgramCharacteristicType generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "link_organization_characteristic_type")
public class LinkOrganizationCharacteristicType implements java.io.Serializable
{

	private int id;
	private Organization organization;
	private CharacteristicType characteristicType;
	private int displayIndex;

	public LinkOrganizationCharacteristicType()
	{
	}

	public LinkOrganizationCharacteristicType(int id, Organization organization,
			CharacteristicType characteristicType, int displayIndex)
	{
		this.id = id;
		this.organization = organization;
		this.characteristicType = characteristicType;
		this.displayIndex = displayIndex;
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organization_id", nullable = false)
	@NotNull
	public Organization getOrganization()
	{
		return this.organization;
	}

	public void setOrganization(Organization organization)
	{
		this.organization = organization;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "characteristic_type_id", nullable = false)
	@NotNull
	public CharacteristicType getCharacteristicType()
	{
		return this.characteristicType;
	}

	public void setCharacteristicType(CharacteristicType characteristicType)
	{
		this.characteristicType = characteristicType;
	}

	@Column(name = "display_index", nullable = false)
	public int getDisplayIndex()
	{
		return this.displayIndex;
	}

	public void setDisplayIndex(int displayIndex)
	{
		this.displayIndex = displayIndex;
	}

}
