package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LinkCourseOfferingOutcomeCharacteristic generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "link_program_program_outcome_characteristic")
public class LinkProgramProgramOutcomeCharacteristic implements java.io.Serializable
{

	private int id;
	private LinkProgramProgramOutcome linkProgramProgramOutcome;
	private Characteristic characteristic;
	private String createdByUserid;
	private Date createdOn;

	public LinkProgramProgramOutcomeCharacteristic()
	{
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "characteristic_id", nullable = false)
	@NotNull
	public Characteristic getCharacteristic()
	{
		return this.characteristic;
	}

	public void setCharacteristic(Characteristic characteristic)
	{
		this.characteristic = characteristic;
	}

	@Column(name = "created_by_userid", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getCreatedByUserid()
	{
		return this.createdByUserid;
	}

	public void setCreatedByUserid(String createdByUserid)
	{
		this.createdByUserid = createdByUserid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 19)
	@NotNull
	public Date getCreatedOn()
	{
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn)
	{
		this.createdOn = createdOn;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "link_program_program_outcome_id", nullable = false)
	@NotNull
	public LinkProgramProgramOutcome getLinkProgramProgramOutcome() {
		return linkProgramProgramOutcome;
	}

	public void setLinkProgramProgramOutcome(LinkProgramProgramOutcome linkProgramProgramOutcome) {
		this.linkProgramProgramOutcome = linkProgramProgramOutcome;
	}

}
