/*****************************************************************************
 * Copyright 2012, 2013 University of Saskatchewan
 *
 * This file is part of the Curriculum Alignment Tool (CAT).
 *
 * CAT is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 *(at your option) any later version.
 *
 * CAT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with CAT.  If not, see <http://www.gnu.org/licenses/>.
 *
 ****************************************************************************/


package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * LinkCourseOfferingAssessment generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "link_assessment_course_outcome")
public class LinkAssessmentCourseOutcome implements java.io.Serializable
{

	private int id;
	private CourseOffering courseOffering;
	private LinkCourseOfferingAssessment assessmentLink;
	private CourseOutcome outcome;	

	public LinkAssessmentCourseOutcome()
	{
	}


	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "course_offering_id", nullable = false)
	@NotNull
	public CourseOffering getCourseOffering()
	{
		return this.courseOffering;
	}

	public void setCourseOffering(CourseOffering courseOffering)
	{
		this.courseOffering = courseOffering;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "link_assessment_course_offering_id", nullable = false)
	@NotNull
	public LinkCourseOfferingAssessment getAssessmentLink() {
		return assessmentLink;
	}


	public void setAssessmentLink(LinkCourseOfferingAssessment assessmentLink) {
		this.assessmentLink = assessmentLink;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "course_outcome_id", nullable = false)
	@NotNull
	public CourseOutcome getOutcome() {
		return outcome;
	}


	public void setOutcome(CourseOutcome outcome) {
		this.outcome = outcome;
	}

}
