package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * LinkCourseOfferingOutcome generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "link_course_contribution_program_outcome")
public class LinkCourseContributionProgramOutcome implements java.io.Serializable
{

	private int id;
	private LinkProgramProgramOutcome linkProgramOutcome;
	private Course course;
	private ContributionOptionValue contribution;
	private MasteryOptionValue mastery;
	
	
	public LinkCourseContributionProgramOutcome()
	{
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "link_program_program_outcome_id", nullable = false)
	@NotNull
	public LinkProgramProgramOutcome getLinkProgramOutcome()
	{
		return this.linkProgramOutcome;
	}

	public void setLinkProgramOutcome(LinkProgramProgramOutcome outcome)
	{
		this.linkProgramOutcome = outcome;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "course_id", nullable = false)
	@NotNull
	public Course getCourse()
	{
		return course;
	}

	public void setCourse(Course course)
	{
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "contribution_option_id")
	public ContributionOptionValue getContribution()
	{
		return contribution;
	}

	public void setContribution(ContributionOptionValue contribution)
	{
		this.contribution = contribution;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mastery_option_id")
	public MasteryOptionValue getMastery() 
	{
		return mastery;
	}

	public void setMastery(MasteryOptionValue mastery) 
	{
		this.mastery = mastery;
	}
}
