package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * LinkCourseOfferingOutcome generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "link_course_outcome_program_outcome")
public class LinkCourseOutcomeProgramOutcome implements java.io.Serializable
{

	private int id;
	private ProgramOutcome programOutcome;
	private CourseOutcome courseOutcome;
	private CourseOffering courseOffering;
	

	
	public LinkCourseOutcomeProgramOutcome()
	{
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "program_outcome_id", nullable = false)
	@NotNull
	public ProgramOutcome getProgramOutcome()
	{
		return this.programOutcome;
	}

	public void setProgramOutcome(ProgramOutcome outcome)
	{
		this.programOutcome = outcome;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "course_outcome_id", nullable = false)
	@NotNull
	public CourseOutcome getCourseOutcome()
	{
		return courseOutcome;
	}

	public void setCourseOutcome(CourseOutcome courseOutcome)
	{
		this.courseOutcome = courseOutcome;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "course_offering_id", nullable = false)
	@NotNull
	public CourseOffering getCourseOffering()
	{
		return courseOffering;
	}

	public void setCourseOffering(CourseOffering courseOffering)
	{
		this.courseOffering = courseOffering;
	}
}
