package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Organization generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "organization")
public class Organization implements java.io.Serializable, Comparable<Organization>
{

	private int id;
	private String name;
	private Organization parentOrganization;
	private Department department;
	private List<Program> programs = new ArrayList<Program>(0);

	public Organization()
	{
	}

	public int compareTo(Organization other)
	{
		return this.name.compareTo(other.getName());
	}
	
	public Organization(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public Organization(int id, String name, List<Program> programs)
	{
		this.id = id;
		this.name = name;
		this.programs = programs;
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "organization")
	@OrderBy("name")
	public List<Program> getPrograms()
	{
		return this.programs;
	}

	public void setPrograms(List<Program> programs)
	{
		this.programs = programs;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "parent_organization_id")
	public Organization getParentOrganization()
	{
		return parentOrganization;
	}

	public void setParentOrganization(Organization parentOrganization)
	{
		this.parentOrganization = parentOrganization;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "department_id")
	public Department getDepartment()
	{
		return department;
	}

	public void setDepartment(Department department)
	{
		this.department = department;
	}
}
