package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Program generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "system_admin")
public class SystemAdmin implements java.io.Serializable
{

	private int id;
	private String name;
	private String lastName;
	private String firstName;
	private String type;
	private String typeDisplay;
	private String createdUserid;
	private Date createdOn;
	
	public SystemAdmin()
	{
	}

	public SystemAdmin(int id, String name)
	{
		this.id = id;
		this.name = name;
	}


	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}



	@Column(name = "type", length = 10)
	@Length(max = 10)
	public String getType()
	{
		return type;
	}

	public void setType(String type)
	{
		this.type = type;
	}
	@Column(name = "created_userid", length = 30)
	@Length(max = 30)
	public String getCreatedUserid()
	{
		return createdUserid;
	}

	public void setCreatedUserid(String createdUserid)
	{
		this.createdUserid = createdUserid;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 19)
	@NotNull
	public Date getCreatedOn()
	{
		return createdOn;
	}

	public void setCreatedOn(Date createdOn)
	{
		this.createdOn = createdOn;
	}

	@Column(name = "type_display", length = 100)
	@Length(max = 100)
	public String getTypeDisplay()
	{
		return typeDisplay;
	}

	public void setTypeDisplay(String typeDisplay)
	{
		this.typeDisplay = typeDisplay;
	}
	@Column(name = "last_name", nullable = true, length = 50)
	@Length(max = 50)
	public String getLastName() 
	{
		return lastName;
	}


	public void setLastName(String lastName) 
	{
		this.lastName = lastName;
	}

	@Column(name = "first_name", nullable = true, length = 50)
	@Length(max = 50)
	public String getFirstName() 
	{
		return firstName;
	}


	public void setFirstName(String firstName) 
	{
		this.firstName = firstName;
	}
}
