package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;



/**
 * Characteristic generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "teaching_method_portion_option")
public class TeachingMethodPortionOption implements java.io.Serializable
{

	private int id;
	private String name;
	private int displayIndex;
	private int comparativeValue;

	public TeachingMethodPortionOption()
	{
	}

	public TeachingMethodPortionOption(int id, String name,int displayIndex)
	{
		this.id = id;
		this.name = name;
		this.displayIndex = displayIndex;
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}
	
	@Column(name = "display_index", nullable = false)
	public int getDisplayIndex()
	{
		return this.displayIndex;
	}

	public void setDisplayIndex(int displayIndex)
	{
		this.displayIndex = displayIndex;
	}
	
	@Column(name = "comparative_value", nullable = false)
	public int getComparativeValue()
	{
		return comparativeValue;
	}

	public void setComparativeValue(int comparativeValue)
	{
		this.comparativeValue = comparativeValue;
	}

}
