package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestTable generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "test_table")
public class TestTable implements java.io.Serializable
{

	private Double x;

	public TestTable()
	{
	}

	public TestTable(Double x)
	{
		this.x = x;
	}

	@Id
	@Column(name = "x", precision = 3, scale = 1)
	public Double getX()
	{
		return this.x;
	}

	public void setX(Double x)
	{
		this.x = x;
	}

}
