/*****************************************************************************
 * Copyright 2012, 2013 University of Saskatchewan
 *
 * This file is part of the Curriculum Alignment Tool (CAT).
 *
 * CAT is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 *(at your option) any later version.
 *
 * CAT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with CAT.  If not, see <http://www.gnu.org/licenses/>.
 *
 ****************************************************************************/


package ca.usask.gmcte.currimap.model.to;

import java.math.BigInteger;

import ca.usask.gmcte.util.HTMLTools;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA




/**
 * Characteristic generated by hbm2java
 */
@SuppressWarnings("serial")

public class ProgramOutcomeCourseContribution implements java.io.Serializable
{

	private int courseId;
	private int programOutcomeId;
	private int contributionSum;
	private int masterySum;
	
	

	public ProgramOutcomeCourseContribution()
	{
	}

	public int getCourseId()
	{
		return courseId;
	}

	public void setCourseId(int courseId)
	{
		this.courseId = courseId;
	}

	public int getProgramOutcomeId()
	{
		return programOutcomeId;
	}

	public void setProgramOutcomeId(int programOutcomeId)
	{
		this.programOutcomeId = programOutcomeId;
	}

	public void setContributionSumObject(Object contributionSum)
	{
		this.contributionSum = getIntValue(contributionSum);
	}
	public void setContributionSum(int contributionSum)
	{
		this.contributionSum = contributionSum;
	}
	public int getContributionSum()
	{
		return contributionSum;
	}
	
	public void setMasterySumObject(Object masterySum)
	{
		this.masterySum = getIntValue(masterySum);
	}
	public void setMasterySum(int masterySum)
	{
		this.masterySum = masterySum;
	}
	public int getMasterySum()
	{
		return masterySum;
	}
	private int getIntValue(Object value)
	{
		String className = value.getClass().getName();
		if(className.equals("java.math.BigInteger"))
		{
			return ((BigInteger)value).intValue();
		}
		else if(className.contains("String"))
		{
			return HTMLTools.getInt((String)value);
		}
		else if(className.contains("Integer"))
		{
			return ((Integer)value);
		}
		System.out.println(className);
		return -1;
	}	
		
}
