/*****************************************************************************
 * Copyright 2012, 2013 University of Saskatchewan
 *
 * This file is part of the Curriculum Alignment Tool (CAT).
 *
 * CAT is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 *(at your option) any later version.
 *
 * CAT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with CAT.  If not, see <http://www.gnu.org/licenses/>.
 *
 ****************************************************************************/


package ca.usask.gmcte.currimap.model;
// Generated Jan 30, 2012 12:54:19 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AnswerOption generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "answer_option")
public class AnswerOption implements java.io.Serializable {

	private Integer id;
	private AnswerSet answerSet;
	private String display;
	private String value;
	private int displayIndex;

	public AnswerOption() {
	}

	public AnswerOption(AnswerSet answerSet, String display, int displayIndex) {
		this.answerSet = answerSet;
		this.display = display;
		this.displayIndex = displayIndex;
	}
	public AnswerOption(AnswerSet answerSet, String display, String value,
			int displayIndex) {
		this.answerSet = answerSet;
		this.display = display;
		this.value = value;
		this.displayIndex = displayIndex;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "answer_set_id", nullable = false)
	@NotNull
	public AnswerSet getAnswerSet() {
		return this.answerSet;
	}

	public void setAnswerSet(AnswerSet answerSet) {
		this.answerSet = answerSet;
	}

	@Column(name = "display", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDisplay() {
		return this.display;
	}

	public void setDisplay(String display) {
		this.display = display;
	}

	@Column(name = "value", length = 100)
	@Length(max = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "display_index", nullable = false)
	public int getDisplayIndex() {
		return this.displayIndex;
	}

	public void setDisplayIndex(int displayIndex) {
		this.displayIndex = displayIndex;
	}

}
