/*****************************************************************************
 * Copyright 2012, 2013 University of Saskatchewan
 *
 * This file is part of the Curriculum Alignment Tool (CAT).
 *
 * CAT is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 *(at your option) any later version.
 *
 * CAT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with CAT.  If not, see <http://www.gnu.org/licenses/>.
 *
 ****************************************************************************/


package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CharacteristicType generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "characteristic_type")
public class CharacteristicType implements java.io.Serializable, Comparable<CharacteristicType>
{

	private int id;
	private String name;
	private String shortDisplay;
	private String valueType;
	private String questionDisplay;
	
	private Set<Characteristic> characteristics = new HashSet<Characteristic>(0);
	private Set<LinkOrganizationCharacteristicType> linkOrganizationmCharacteristicTypes = new HashSet<LinkOrganizationCharacteristicType>(
			0);

	public CharacteristicType()
	{
	}
	public int compareTo(CharacteristicType other)
	{
		return other.getId()-id;
	}

	public CharacteristicType(int id, String name, String valueType)
	{
		this.id = id;
		this.name = name;
		this.valueType = valueType;
	}

	public CharacteristicType(int id, String name, String valueType,
			Set<Characteristic> characteristics,
			Set<LinkOrganizationCharacteristicType> linkOrganizationCharacteristicTypes)
	{
		this.id = id;
		this.name = name;
		this.valueType = valueType;
		this.characteristics = characteristics;
		this.linkOrganizationmCharacteristicTypes = linkOrganizationCharacteristicTypes;
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}
	
	@Column(name = "question_display", nullable = true, length = 100)
	@Length(max = 200)
	public String getQuestionDisplay()
	{
		return this.questionDisplay;
	}

	public void setQuestionDisplay(String q)
	{
		this.questionDisplay = q;
	}

	@Column(name = "value_type", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getValueType()
	{
		return this.valueType;
	}

	public void setValueType(String valueType)
	{
		this.valueType = valueType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "characteristicType")
	public Set<Characteristic> getCharacteristics()
	{
		return this.characteristics;
	}

	public void setCharacteristics(Set<Characteristic> characteristics)
	{
		this.characteristics = characteristics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "characteristicType")
	public Set<LinkOrganizationCharacteristicType> getLinkOrganizationCharacteristicTypes()
	{
		return this.linkOrganizationmCharacteristicTypes;
	}

	public void setLinkOrganizationCharacteristicTypes(
			Set<LinkOrganizationCharacteristicType> linkProgramCharacteristicTypes)
	{
		this.linkOrganizationmCharacteristicTypes = linkProgramCharacteristicTypes;
	}
	@Column(name = "short_display", nullable = false, length = 32)
	@NotNull
	@Length(max = 32)
	public String getShortDisplay()
	{
		return this.shortDisplay;
	}

	public void setShortDisplay(String shortDisplay)
	{
		this.shortDisplay = shortDisplay;
	}
}
