/*****************************************************************************
 * Copyright 2012, 2013 University of Saskatchewan
 *
 * This file is part of the Curriculum Alignment Tool (CAT).
 *
 * CAT is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 *(at your option) any later version.
 *
 * CAT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with CAT.  If not, see <http://www.gnu.org/licenses/>.
 *
 ****************************************************************************/


package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Outcome generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "course_outcome")
public class CourseOutcome implements java.io.Serializable, Comparable<CourseOutcome>
{

	private int id;
	private String name;
	private String description;
	private Set<LinkCourseOfferingOutcome> linkCourseOfferingOutcomes = new HashSet<LinkCourseOfferingOutcome>(0);

	public CourseOutcome()
	{
	}

	public int compareTo(CourseOutcome other)
	{
		return other.getId() - id;
	}
	
	public CourseOutcome(int id, String name)
	{
		this.id = id;
		this.name = name;
	}


	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 400)
	@NotNull
	@Length(max = 400)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "description", length = 1024)
	@Length(max = 1024)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseOutcome")
	public Set<LinkCourseOfferingOutcome> getLinkCourseOfferingOutcomes()
	{
		return this.linkCourseOfferingOutcomes;
	}

	public void setLinkCourseOfferingOutcomes(Set<LinkCourseOfferingOutcome> linkCourseOfferingOutcomes)
	{
		this.linkCourseOfferingOutcomes = linkCourseOfferingOutcomes;
	}
}
