/*****************************************************************************
 * Copyright 2012, 2013 University of Saskatchewan
 *
 * This file is part of the Curriculum Alignment Tool (CAT).
 *
 * CAT is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 *(at your option) any later version.
 *
 * CAT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with CAT.  If not, see <http://www.gnu.org/licenses/>.
 *
 ****************************************************************************/


package ca.usask.gmcte.currimap.model;

// Generated Dec 3, 2011 11:40:19 AM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import ca.usask.gmcte.currimap.action.ProgramManager;

/**
 * Organization generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "organization")
public class Organization implements java.io.Serializable, Comparable<Organization>
{

	private int id;
	private String name;
	private Organization parentOrganization;
	private String systemName;
	private String active;
	private List<Program> programs = new ArrayList<Program>(0);
	private List<CharacteristicType> characteristicTypes;
	private List<LinkOrganizationCharacteristicType> linkOrganizationCharacteristicTypes = new ArrayList<LinkOrganizationCharacteristicType>(0);

	public Organization()
	{
	}

	public int compareTo(Organization other)
	{
		return this.name.compareTo(other.getName());
	}
	
	public Organization(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public Organization(int id, String name, List<Program> programs)
	{
		this.id = id;
		this.name = name;
		this.programs = programs;
	}

	@Id @GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "organization")
	@OrderBy("name")
	public List<Program> getPrograms()
	{
		return this.programs;
	}

	public void setPrograms(List<Program> programs)
	{
		this.programs = programs;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "parent_organization_id")
	public Organization getParentOrganization()
	{
		return parentOrganization;
	}

	public void setParentOrganization(Organization parentOrganization)
	{
		this.parentOrganization = parentOrganization;
	}
	

	@Column(name = "system_name", nullable = true, length = 255)
	@Length(max = 255)
	public String getSystemName() {
		return systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}
	
	@Column(name = "active", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getActive() {
		return active;
	}

	public void setActive(String active) {
		this.active = active;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organization")
	public List<LinkOrganizationCharacteristicType> getLinkOrganizationCharacteristicTypes()
	{
		return this.linkOrganizationCharacteristicTypes;
	}

	public void setLinkOrganizationCharacteristicTypes(
			List<LinkOrganizationCharacteristicType> linkOrganizationCharacteristicTypes)
	{
		this.linkOrganizationCharacteristicTypes = linkOrganizationCharacteristicTypes;
	}

	@Transient
	public List<CharacteristicType> getCharacteristicTypes()
	{
		if(characteristicTypes == null)
		{
			ProgramManager.instance().setOrganizationCharacteristicTypes(this);
		}
		return characteristicTypes;
	}

	public void setCharacteristicTypes(List<CharacteristicType> characteristicTypes)
	{
		this.characteristicTypes = characteristicTypes;
	}
	
}
